application:
  name: mern-backend
  project: project-account
  organization: QoveryCommunity
  publicly_accessible: true
  port: 3000
routers:
- name: main
  routes:
  - application_name: mern-backend
    paths:
    - /
