---
application:
  name: "mern-backend"
  project: "project-account"
  organization: "QoveryCommunity"
  publicly_accessible: true
routers:
- name: "main-mern-backend"
  routes:
  - application_name: "mern-backend"
    paths:
    - "/*"
